name: AutoMessageBuilder
version: 1.0.0
main: io.com.automessagebuilder.AutoMessageBuilder 
description: Messaging Plugin
author: lit.dll
website: https://papermc.io
api-version: '1.20'


commands:
  automessage:
    description: "Controla los mensajes automáticos"
    usage: |
      /automessage set <id> <mensaje> <interval> - Inicia los mensajes
      /automessage delete <id>  - Borra mensajes
      /automessage list - Muestra todos los mensajes
      
    permission: 
      automessagebuilder.use
      automessagebuilder.delete
      automessagebuilder.list
      automessagebuilder.add
      
    aliases: [ "am" ]